### ISSUE TITLE
The initial `dev-*` into `release-*` pipeline for a new `*-configs` repository is difficult

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/model-config-tests#58]
See https://github.com/ACCESS-NRI/model-config-tests/pull/56#issuecomment-2319606419

Currently, we have to create `release-*` config branches on top of `dev-*` then push a boring commit to activate the `config-pr-3-bump-tag.yml` workflow (which is `on.push.paths=metadata.yaml`). 

See if we can make this a bit more streamlined, maybe with a `on.create` trigger for `release-*` branches?

## TODOs

 - [x] Modify CI for `access-om2-configs`. See https://github.com/ACCESS-NRI/access-om2-configs/pull/140
 - [x] Modify CI for `access-esm1.5-configs`. See https://github.com/ACCESS-NRI/access-esm1.5-configs/pull/91
 - [x] Modify CI for `access-esm1.6-configs`. See https://github.com/ACCESS-NRI/access-esm1.6-configs/pull/2
 - [x] Modify CI for `access-om3[-wav]-configs` if created before then. Note: Not required. 
 - [x] Modify CI for template `model-configs-template`. See https://github.com/ACCESS-NRI/model-configs-template/pull/3
 - [x] Update potential triggers in `model-config-tests` `config-pr-3-bump-tag.yml`. See https://github.com/ACCESS-NRI/model-config-tests/pull/62

**Comment by CodeGat** [comment]
Closing as the above PRs are merged!
